import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  title: {
    fontSize: 20,
    alignSelf: 'center',
    color: '#4B0082',
    fontWeight: 'bold',
    fontFamily: 'Roboto',
  },
  button: {
    width: '90%',
    height: 50,
    backgroundColor: '#4B0082',
    marginTop: 25,
    borderRadius: 4,
    alignItems: 'center',
    alignSelf: 'center',
  },
  button2: {
    width: '90%',
    height: 70,
    backgroundColor: '#4B0082',
    marginTop: 25,
    borderRadius: 4,
    alignItems: 'center',
    alignSelf: 'center',
  },
  textTopo: {
    fontSize: 30,
    alignSelf: 'center',
    color: '#4B0082',
    fontWeight: 'bold',
    marginTop: 23,
    fontFamily: 'Roboto',
  },
  topo: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: '1.5%',
  },
  textTopo1: {
    marginTop: 5,
    fontSize: 20,
    color: '#fff',
  },
  cardT1: {
    marginTop: 20,
    borderWidth: 2,
    borderColor: '#4B0082',
    width: '90%',
    height: 200,
    backgroundColor: 'white',
    borderRadius: 5,
    alignSelf: 'center',
  },
  cardT2: {
    marginTop: 20,
    borderWidth: 2,
    borderColor: '#4B0082',
    width: '90%',
    height: 200,
    backgroundColor: 'white',
    borderRadius: 5,
    alignSelf: 'center',
  },
  cardSubtitleT1: {
    top: 0,
    right: 0,
    left: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: '#4B0082',
    height: 50,
  },

  cardTable: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginBottom: '1.5%',
    marginLeft: 10,
    marginTop: 10,
  },
  cardTable2: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
    marginBottom: '1.5%',
    marginLeft: 10,
    marginTop: 10,
  },
  cardTableTitle: {
    fontSize: 18,
    color: '#4B0082',
  },
  txtCard: {
    fontFamily: 'Roboto',
    fontSize: 15,
  },
  text: {
    color: '#fff',
    textAlign: 'center',
    marginTop: 15,
    alignItems: 'center',
  },
  paddingText: {
    paddingTop: 6,
    fontWeight: 'bold',
    fontSize: 16,
    color: '#212f3d',
  },
  searchBar: {
    width: '90%',
    alignSelf: 'center',
  },
});
